version: "3.7"
services:
  seba:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    env_file:
      - .env
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./src/worker.py
    volumes:
      - ./:/src
    env_file:
      - .env